// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoVw6tCncrSrENExi-PCpb_pwocXz9WcM',
    appId: '1:504264663092:web:0e09edbad9637d71c4aa61',
    messagingSenderId: '504264663092',
    projectId: 'msgboard-9af49',
    authDomain: 'msgboard-9af49.firebaseapp.com',
    storageBucket: 'msgboard-9af49.firebasestorage.app',
    measurementId: 'G-3SGBD83GB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7Pp-7cxu8uAFAy9EiypHWkoJWsN7SkY8',
    appId: '1:504264663092:android:c2f60fcbb542f6a4c4aa61',
    messagingSenderId: '504264663092',
    projectId: 'msgboard-9af49',
    storageBucket: 'msgboard-9af49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJbbVq_V0yuXeBkt4ZO66dvN5JM7F7Zsg',
    appId: '1:504264663092:ios:d64ff597e108e122c4aa61',
    messagingSenderId: '504264663092',
    projectId: 'msgboard-9af49',
    storageBucket: 'msgboard-9af49.firebasestorage.app',
    iosBundleId: 'com.example.msgboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJbbVq_V0yuXeBkt4ZO66dvN5JM7F7Zsg',
    appId: '1:504264663092:ios:d64ff597e108e122c4aa61',
    messagingSenderId: '504264663092',
    projectId: 'msgboard-9af49',
    storageBucket: 'msgboard-9af49.firebasestorage.app',
    iosBundleId: 'com.example.msgboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoVw6tCncrSrENExi-PCpb_pwocXz9WcM',
    appId: '1:504264663092:web:cd188e8263683bcec4aa61',
    messagingSenderId: '504264663092',
    projectId: 'msgboard-9af49',
    authDomain: 'msgboard-9af49.firebaseapp.com',
    storageBucket: 'msgboard-9af49.firebasestorage.app',
    measurementId: 'G-717F91CB8G',
  );
}
